<?php

function get_form_tarjeta_de_produccion() {
  module_load_include('inc', 'node', 'node.pages'); 
  $node_form = new stdClass;
  $node_form->type = 'tarjeta_de_produccion';
  $node_form->language = LANGUAGE_NONE;
  $form = drupal_get_form('tarjeta_de_produccion_node_form', $node_form);
 return drupal_render($form);
}

function custom_functions_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == "tarjeta_de_produccion_node_form"){
    $b = 0;
    $form['phone'] = array(
      '#title'    => t('Phone'),
      '#type'     => 'textfield',
      '#required' => TRUE,
    );
  }
}

function get_corte_values($data, $row, $nid = 0){
  $resp = new stdClass();
  $resp->suma_color_capa = 0;
  $resp->suma_total = 0;
  if($nid == 0){
    $node = node_load($data->nid);
  } else {
    $node = node_load($nid);
  }
  $items_cc = field_get_items('node', $node, 'field_color_y_capa');
  
  $i = 0;
  $resp->cc = array();
  $resp->html_cc = '<table><thead><tr><th>Color</th><th>Capas</th></tr></thead><tbody>';
  foreach ($items_cc as $item) {
    $fc = field_collection_field_get_entity($item);
    $term = taxonomy_term_load($fc->field_color[LANGUAGE_NONE][0]['tid']);
    $resp->cc[$i] = new stdClass();
    $resp->cc[$i]->color_tid = $term->tid;
    $resp->cc[$i]->color = $term->name;
    $resp->cc[$i]->capa = $fc->field_capas[LANGUAGE_NONE][0]['value'];
    $resp->html_cc .= '<tr><td>' . $resp->cc[$i]->color .'</td><td>' . $resp->cc[$i]->capa . '</td></tr>';
    $resp->suma_color_capa = $resp->suma_color_capa + $fc->field_capas[LANGUAGE_NONE][0]['value'];    
    $i++;
  }
  $resp->html_cc .= '</tbody><tfoot><tr><td>Total: </td><td>' . $resp->suma_color_capa . '</td></tr></tfoot></table>';
  
  
  
  $items_tt = field_get_items('node', $node, 'field_talla_y_tanto');
  $i = 0;
  $resp->tt = array();
  $resp->html_tt = '<table><thead><tr><th>Talla</th><th>Tanto</th><th>Subtotal</th></tr></thead><tbody>';
  foreach ($items_tt as $item) {    
    $fc = field_collection_field_get_entity($item);
    $term = taxonomy_term_load($fc->field_talla[LANGUAGE_NONE][0]['tid']);
    $resp->tt[$i] = new stdClass();
    $resp->tt[$i]->talla_tid = $term->tid;
    $resp->tt[$i]->talla = $term->name;
    $resp->tt[$i]->tanto = $fc->field_tanto[LANGUAGE_NONE][0]['value'];
    $resp->html_tt .= '<tr><td>' . $resp->tt[$i]->talla .'</td><td>' . $resp->tt[$i]->tanto . '</td><td>' . ($resp->tt[$i]->tanto * $resp->suma_color_capa) . '</td></tr>';
    $resp->suma_total = $resp->suma_total + ($resp->tt[$i]->tanto * $resp->suma_color_capa);
    $i++;
  }
  $resp->html_tt .= '</tbody><tfoot><tr><td></td><td>Total: </td><td>' . $resp->suma_total . '</td></tr></tfoot></table>';
  
  $resp->html_actions = getActionsLinks($node);
  
  return $resp;
}

function getActionsLinks($node){
  $resp = new stdClass();
  $resp->nueva_tarjeta_produccion = l('Crear Tarjeta de Producción', 't-produccion/' . $node->nid);
  return $resp;
}
